### ISSUE TITLE
gtk/ButtonClickTest hangs infinitely

### ISSUE THREAD

**Issue by mchalupa** [01org/wayland-fits#8]
When I run this test, it just timeouts, waiting for:

wfits_query@23.surface_geometry(wl_surface@3, new id wfits_query_result@18)

I debugged the test and found out that there is nothing dispatching wayland events. The test gets the registry and does one roundtrip. After that it queues wl_registry.bind requests but never sends them to server and sleeps in YIELD_UNTIL().

From the code it looks like there should be another thread that is dispatching events, because YIELD_UNTIL() just calls usleep() in a loop until a callback comes. gdb says that there is no such other thread.

**Comment by uartie** [comment]
Thanks for reporting this issue.  It looks like you've created a patch in your forked wayland-fits.  Nice find.  I can merge it to master here if you'd like.  Please create a pull request if so.
